config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'  
get 'foods' => 'foods#index', as: :foods_index
delete 'foods/:id' => 'foods#destroy', as: :deletef
post 'foods/:id' => 'foods#destroy'
get 'meals' => 'meals#index', as: :meals_index
delete 'meals/:id' => 'meals#destroy', as: :deletem
post 'meals/:id' => 'meals#destroy'
get 'choosers' => 'choosers#index', as: :choosers_index
delete 'choosers/:id' => 'choosers#destroy', as: :deleter
post 'choosers/:id' => 'choosers#destroy'
get 'choosers/groceries' => 'choosers#groceries'
resources :foods, :meals, :choosers

end

app/models/chooser.rb
class Chooser < ActiveRecord::Base
    has_many :meals
end

app/models/foods.rb
class Foods < ActiveRecord::Base
    belongs_to :meals
    default_scope { order(food_name: :asc)}
end

app/models/meals.rb
class Meals < ActiveRecord::Base
    has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choosers_controller.rb
class ChoosersController < ApplicationController
    def index
        @choosers = Chooser.all
    end
  def new
  @chooser = Chooser.new
  end
  def create
  @chooser = Chooser.new(chooser_params)
    if @chooser.save
    redirect_to '/choosers'
    else
    render '/choosers/new'
    end
  end
  def show
  @chooser = Chooser.find(params[:id])
  end
  def edit
  @chooser = Chooser.find(params[:id])
  end
  def update
 # Find object using form parameters
 @chooser = Chooser.find(params[:id])
   # Update the object
   if @chooser.update_attributes(chooser_params)
   # If update succeeds, redirect to the list action
   flash[:sucess] = "Chooser Item updated."
   redirect_to(:action => 'index')
   else
   # If save fails, redisplay the form so user can fix problems
   render('edit')
   end
  end
  def destroy
  @chooser = Chooser.find(params[:id]).destroy
  flash[:success] = "Chooser Item deleted."
  redirect_to(:action => 'index')
  end
  def groceries
    @choosers = Chooser.all      
  end
  

private
  def chooser_params
  params.require(:chooser).permit(:chooser, :day, :breakfast, :lunch, :supper)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
  @foods = Foods.all
  end
  
  def new
  @food = Foods.new
  end
  
  def create
  @food = Foods.new(food_params)
    if @food.save
      redirect_to '/foods'
    else
      render '/foods/new'
    end
  end
  
  def show
    @food = Foods.find(params[:id])
  end
  
  def edit
    @food = Foods.find(params[:id])
  end
  
  def update
 # Find object using form parameters
    @food = Foods.find(params[:id])
   # Update the object
    if @food.update_attributes(food_params)
   # If update succeeds, redirect to the list action
      flash[:sucess] = "Food Item updated."
      redirect_to(:action => 'index')
    else
   # If save fails, redisplay the form so user can fix problems
    render('edit')
    end
  end
  
  def destroy
  @food = Foods.find(params[:id]).destroy
  flash[:success] = "Food Item deleted."
  redirect_to(:action => 'index')
  end

private
  def food_params
  params.require(:foods).permit(:foods, :food_id, :food_name, :cost, :unit_qty)
  end
  
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
  @meals = Meals.all
  end
  def new
  @meal = Meals.new
  end
  def create
  @meal = Meals.new(meal_params)
    if @meal.save
    redirect_to '/meals'
    else
    render '/meals/new'
    end
  end
  def show
  @meal = Meals.find(params[:id])
  end
  def edit
  @meal = Meals.find(params[:id])
  end
  def update
 # Find object using form parameters
 @meal = Meals.find(params[:id])
   # Update the object
   if @meal.update_attributes(meal_params)
   # If update succeeds, redirect to the list action
   flash[:sucess] = "Meal Item updated."
   redirect_to(:action => 'index')
   else
   # If save fails, redisplay the form so user can fix problems
   render('edit')
   end
  end
  def destroy
  @meal = Meals.find(params[:id]).destroy
  flash[:success] = "Meal Item deleted."
  redirect_to(:action => 'index')
  end

private
  def meal_params
  params.require(:meals).permit(:meals, :image, :meal_name, :category, :prep_time, :servings, :food_id => [])
  end

end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
    def index
        @recipies = Recipie.all
    end
  def new
  @recipie = Recipie.new
  end
  def create
  @recipie = Recipie.new(recipie_params)
    if @recipie.save
    redirect_to '/recipies'
    else
    render '/recipies/new'
    end
  end
  def show
  @recipie = Recipie.find(params[:id])
  end
  def edit
  @recipie = Recipie.find(params[:id])
  end
  def update
 # Find object using form parameters
 @recipie = Recipie.find(params[:id])
   # Update the object
   if @recipie.update_attributes(recipie_params)
   # If update succeeds, redirect to the list action
   flash[:sucess] = "Recipie Item updated."
   redirect_to(:action => 'index')
   else
   # If save fails, redisplay the form so user can fix problems
   render('edit')
   end
  end
  def destroy
  @recipie = Recipie.find(params[:id]).destroy
  flash[:success] = "Recipie Item deleted."
  redirect_to(:action => 'index')
  end

private
  def recipie_params
  params.require(:recipie).permit(:recipie, :image, :meal_id, :meal_name, {:food_id => []}, :instructions)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/choosers_helper.rb
module ChoosersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/choosers/_form.html.erb
<div class="header">
<%= image_tag ("food.jpg") %>
 <div class="container">

 </div>
</div>

<div class="form">
 <div class="container">
 
<%= form_for(@chooser) do |c| %>
<p>
<%= c.label(:day, "Day of Week") %><br>
<%= c.text_field(:day) %>
</p>
<p>
<%= c.label(:breakfast) %>
<%= c.collection_select(:breakfast, Meals.all, :id, :meal_name, :include_blank => "Please select") %>
</p>
<p>
<%= c.label(:lunch) %>
<%= c.collection_select(:lunch, Meals.all, :id, :meal_name, :include_blank => "Please select") %>
</p>
<p>
<%= c.label(:supper) %>
<%= c.collection_select(:supper, Meals.all, :id, :meal_name, :include_blank => "Please select") %>
</p>
<p>
 <%= c.submit "Save Changes" %> <button type="submit" formaction="javascript:history.go(-1);">Cancel</button>
</p>
 <% end %>  
  </div>
</div>

app/views/choosers/edit.html.erb
<div class="header">
 <div class="container">
   
<h1>Edit Meal Selection</h>
<%= render 'form' %>
 </div>
</div>

app/views/choosers/groceries.html.erb
<body data-gr-c-s-loaded="true">

<style>
 .inline {
 display: inline;
 }
</style>
<div class="header">
<center><%= image_tag ("menu.jpg") %></center>
 <div class="container">
   
   <center><h1>Weekly Grocery List</h>
   <h2><%= link_to "Plan a New Day", new_chooser_path() %>    <%= link_to "Main Menu", '/' %></h2></center>
 </div>
</div>

<div class="glist">
 <center><div class="container">

 <table border = 1>
 	<tr>
 		<td><h3><center>Selected</center></h3></td>
 		<td><h3><center>Food Item</center></h3></td>
 		<td><h3><center>Quantity</center></h3>
 		<td><h3><center>Unit Cost</center></h3></td>
 		<td><h3><center>Total Item Cost</center></h3>
 	<% marray = [] %>
  <% @choosers.each do |c, meal| %>
  <% farray = [c.breakfast, c.lunch, c.supper] %>
  <% marray = marray + farray %>
  <% end %>
  <% garray = [] %>
  <% marray.each do |m| %>
  <% mealselect = Meals.find(m) %>
  <% intarray = mealselect.food_id %>
  <% garray = garray + intarray %>
  <% end %>
  <% #garray = garray.uniq %>
  <% garray = garray.compact %>
  <% print garray %>
  <% ghash = {} %>
  <% for i in 0..garray.length-1 %>
  <% if ghash[garray[i]] == nil
      ghash[garray[i]] = 1
     else
      ghash[garray[i]] = 1 + ghash[garray[i]]
     end
    end
  %>
  <% print ghash.compact %>
  <% #ghash = ghash.compact %>
  <% totalCost = 0 %>
  <% x = 0 %>    
  <% ghash.each do |i, q| %>
  <% gfind = Foods.find(i) %>
  <tr id="row_<%=x %>">
		 <td><b><input type="checkbox" checked="checked" id="item_checked_<%=x %>"></b></td>
		 <td><%= gfind.food_name %></td>
		 <td><%= q %></td>
		 <% fcost = (gfind.cost.to_f * q) %>
   <td><%= number_with_precision(gfind.cost, precision: 2) %></td>
		 <td id="cost_<%=x %>"><%= number_with_precision(fcost, precision: 2) %></td>
	 </tr>
	 <% x = x + 1 %>
	 <% totalCost = fcost + totalCost %>
  <% end %>
	 </table>
	
 <p><b class = "inline">Approximate Grocery Total: $
    <span class = "inline" id = "item_total"></span></b><br>
    <input class = "inline" id = "recalc" type = "button" value = "Recalculate Cost"><br>
    <input class = "inline" id = "repost" type = "button" value = "Repost List"><br>
    <input class = "inline" id = "print_list" type = "button" value = "Print List"></p>
		</center>
 </div>
</div>
<script>
 function addPrices() {
  var total = 0;
  var long = <%=garray.length %>;
  for (var i = 0; i <= long; i++) {
   var selected = $('#item_checked_' + i);
   if(selected.prop('checked') == true) {
    var rowVal = parseFloat($('#cost_'+ i).html());
   } else {
    var rowVal = 0;
   }
   total += rowVal;
  }
  $('#item_total').html(total.toFixed(2));
 }
 function hideLines() {
  var long = <%=garray.length %>;
  for (var i = 0; i <= long; i++) {
   var rowSel = $('#item_checked_' + i);
   if(rowSel.prop('checked') != true) {
    $('#row_' + i).hide();
   } else {
    $('#row_' + i).show();
   }
  }
 }
 function doMultiple() {
  addPrices();
  hideLines();
 }
 function printButton() {
  window.print();
 }
 
 $(document).ready(addPrices);
 $('#recalc').click(addPrices);
 $('#repost').click(doMultiple);
 $('#print_list').click(printButton);
</script>
</body>

app/views/choosers/index.html.erb
<div class="header">
<center><%= image_tag ("menu.jpg") %></center>
 <div class="container">
   
   <center><h1>Weekly Meal Planner</h>
   <h2><%= link_to "Plan a New Day", new_chooser_path() %>    <%= link_to "Main Menu", '/' %><br><br>
   <%= link_to "View/Print the Grocery List", choosers_groceries_path() %></h2></center>
 </div>
</div>

<div class="mplanner">
 <center><div class="container">

 <table border = 1>
 	<tr>
 		<td><h3><center>Day</center></h3></td>
 		<td><h3><center>Breakfast</center></h3></td>
 		<td><h3><center>Lunch</center></h3></td>
 		<td><h3><center>Supper</center></h3></td>
 		<td><h3><center>Actions</center></h3></td>
 	</tr>
  <% @choosers.order(:id).each do |c, meal| %>
  	<tr>
		<td><b><%= c.day %></b></td>
		<td><% bname = Meals.find(c.breakfast) %>
		    <%= bname.meal_name %></td>
		<td><% lname = Meals.find(c.lunch) %>
		    <%= lname.meal_name %></td>
		<td><% sname = Meals.find(c.supper) %>
		    <%= sname.meal_name %></td>
		<td><%= link_to "Edit", edit_chooser_path(c) %>  <%= link_to "Delete", c, method: :deletem, data: {confirm: "Are you sure?" } %></td>
	</tr>
  
<% end %>

		</center>
 </div>
</div>

app/views/choosers/new.html.erb
<div class="header">
 <div class="container">
  
<h1>Meals Selector</h>
<%= render 'form' %>

 </div>
</div>

app/views/foods/_form.html.erb
<div class="header">
<%= image_tag ("food.jpg") %>
 <div class="container">

 </div>
</div>

<div class="form">
 <div class="container">
 
<%= form_for(@food) do |f| %>
<p>
<%=  f.label(:food_name, "Food Name") %><br>
<%= f.text_field(:food_name) %>
</p>

<p>
<%=  f.label(:cost, "Cost") %><br>
<%= f.number_field :cost, value: number_to_currency(f.object.cost.to_f, delimiter: '', unit: ''), step: :any %>
</p>
<p>
<%=  f.label(:unit_qty, "Unit QTY") %><br>
<%= f.text_field(:unit_qty) %>
</p>
<p>
 <%= f.submit "Save Changes" %>  <button type="submit" formaction="javascript:history.go(-1);">Cancel</button>
</p>
 <% end %>  
  </div>
</div>

app/views/foods/edit.html.erb
<div class="header">
 <div class="container">
   
<h1>Edit Food Item</h>
<%= render 'form' %>
 </div>
</div>

app/views/foods/index.html.erb
<style>
 .inline
</style>
<div class="header">
<center><%= image_tag ("food.jpg") %></center>
 <div class="container">
   
   <center><h1>Food List</h>
   <h2><%= link_to "Add New Food Item", 'foods/new' %>    <%= link_to "Main Menu", '/' %></h2></center>
 </div>
</div>

<div class="flist">
 <center><div class="container">

 <table border = 1>
 	<tr>
 		<td><h3>Name</h3></td>
 		<td><h3>Cost</h3></td>
 		<td><h3>Unit QTY</h3></td>
 		<td><h3>Actions</h3></td>
 	</tr>
  <% @foods.order(:food_name).each do |food| %>
  	<tr>
		<td><%= food.food_name %></td>
		<td><%=number_to_currency(food.cost) %></td>
		<td><%=food.unit_qty %></td>
		<td><%= link_to "Edit", edit_food_path(food) %>  <%= link_to "Delete", food, method: :deletef, data: {confirm: "Are you sure?" } %></td>
	</tr>
<% end %>
 </table>
		</center>
 </div>
</div>

app/views/foods/new.html.erb
<div class="header">
 <div class="container">
  
<h1>New Food Item</h>
<%= render 'form' %>

 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grocery Planning App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'jquery', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<div class="header">
<%= image_tag ("menu.jpg") %>
 <div class="container">

 </div>
</div>

<div class="form">
 <div class="container">
 
<%= form_for(@meal) do |f| %>
<p>
 <%= f.label(:image, "Image") %><br>
 <%= f.text_field(:image) %>
</p>
<p>
<%=  f.label(:meal_name, "Meal Name") %><br>
<%= f.text_field(:meal_name) %>
</p>
<p>
 <%=  f.label(:category, "Category") %><br>
<%= f.text_field(:category) %>
</p>
<p>
 <%= f.label(:servings, "Number of Servings") %><br>
 <%= f.number_field :servings %>
</p>
<p>
<%=  f.label(:prep_time, "Prep Time") %><br>
<%= f.text_field(:prep_time) %>
</p>

<table>
<tr>
 <td>
 <%=  f.label(:food_id, "Ingredients") %></td>
</tr>
<tr>
 <td><p style="font-size: 15px">
 <%= f.collection_check_boxes(:food_id, Foods.all, :id, :food_name, {:include_blank => false}, {:multiple => true}) do |b| %> 
 <%= b.label(":data-value" => b.value) { b.check_box + b.text } %><br>
 <% end %></p></td>
  </tr>
</table>
<p>
 <%= f.submit "Save Changes" %> <button type="submit" formaction="javascript:history.go(-1);">Cancel</button>
</p>
 <% end %>  
  </div>
</div>

app/views/meals/edit.html.erb
<div class="header">
 <div class="container">
   
<h1>Edit Menu Item</h>
<%= render 'form' %>
 </div>
</div>

app/views/meals/index.html.erb
<div class="header">
<center><%= image_tag ("menu.jpg") %></center>
 <div class="container">
   
   <center><h1>Meal List</h>
   <h2><%= link_to "Add New Meal Item", new_meal_path() %>    <%= link_to "Main Menu", '/' %></h2></center>
 </div>
</div>

<div class="mlist">
 <center><div class="container">

 <table border = 1>
 	<tr>
 		<td><h3>Image</h3></td>
 		<td><h3>Meal Name</h3></td>
 		<td><h3>Category</h3></td>
 		<td><h3>Number of Servings</h3></td>
 		<td><h3>Ingredients</h3></td>
 		<td><h3>Prep Time</h3></td>
 		<td><h3>Actions</h3></td>
 	</tr>
  <% @meals.order(:meal_name).each do |m, food| %>
  	<tr>
		<td><%= image_tag(m.image, size: "75x50") %></td>
		<td><%=m.meal_name %></td>
		<td><%=m.category %></td>
		<td><%=m.servings %></td>
		<td><% m.food_id.compact.each do |id| %>
			<% fname = Foods.find(id) %>
			<%=fname.food_name %><br>
			<% end %></td>
		<td><%=m.prep_time %></td>
		<td><%= link_to "Edit", edit_meal_path(m) %>  <%= link_to "Delete", m, method: :deletem, data: {confirm: "Are you sure?" } %></td>
	</tr>
  
<% end %>
		</center>
 </div>
</div>

app/views/meals/new.html.erb
<div class="header">
 <div class="container">
  
<h1>New Menu Item</h>
<%= render 'form' %>

 </div>
</div>

app/views/welcome/index.html.erb
<head>
    <title>Grocery Planning App</title>
</head>

<h1><center>Welcome to the Grocery Menu App!</center></h1>
<h2><center>Please feel free to check back often as I continue updating the app.</center></h2>
<h3><li>Food List Master for Grocery Pricing and purchase quantities: <%=link_to"Food List", 'foods#index' %></li></h3>
<h3><li>Meals/Menu List Master for Meal Planning with Ingredients and Prep Times: <%=link_to"Meals List", 'meals#index' %></li></h3>
<h3><li>Meal Planning List: <%=link_to"Meals Chooser List", 'choosers#index' %></li></h3>
<h3><li>Weekly Grocery List for Preview and Printing: <%= link_to "Grocery List", 'choosers/groceries' %></li></h3>